### ISSUE TITLE
pls read

### ISSUE THREAD

**Issue by Dentamon** [ZasticBradyn/Blooket-Hacks#2]
Hi, me again.  Sorry!  I just want to tell you, I am going to make you a contributor on my Blooket hacks, so pls don't remove stuff right now.  once you have finished coding your hacks, can you please change mine from gliz's to yours?  I hope you can :)
-Dentamon

**Comment by ZasticBradyn** [comment]
Yeah, I can do that, before i saw this issue i moved your hacks into a folder. ill put my scripts into your repository.
